backend:
  name: git-gateway
  branch: master
media_folder: 'assets/uploads'
collections:
  - name: 'pages'
    label: 'Pages'
    folder: '/'
    fields:
      - { label: "Layout" , name : "layout"}
      - { label: "Homepage" , name : "homepage", widget: "boolean"}
      - { label: "Contact", name : "body", widget: 'markdown' }
