
on: push

name: Publish Website Dry Run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Jekyll build
      run: jekyll build
    - name: List files
      run: ls -al
    - name: Location
      run: pwd
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ftp.damongolding.com
        FTP_USERNAME: github@damongolding.com
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        LOCAL_DIR: docs
        ARGS: --dry-run
